# Generated by Django 4.2.16 on 2024-10-04 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userProfiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('age', models.IntegerField()),
                ('height', models.DecimalField(decimal_places=2, max_digits=6)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fitnessgoals', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='healthData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_recorded', models.DateTimeField(auto_now_add=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('bmi', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('blood_pressure', models.CharField(max_length=7)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.userprofiles')),
            ],
        ),
    ]
