# Generated by Django 5.1.2 on 2024-11-22 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_userprofile_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('day1_workout', models.TextField()),
                ('day1_diet', models.TextField()),
                ('day2_workout', models.TextField()),
                ('day2_diet', models.TextField()),
                ('day3_workout', models.TextField()),
                ('day3_diet', models.TextField()),
                ('day4_workout', models.TextField()),
                ('day4_diet', models.TextField()),
                ('day5_workout', models.TextField()),
                ('day5_diet', models.TextField()),
                ('day6_workout', models.TextField()),
                ('day6_diet', models.TextField()),
                ('day7_workout', models.TextField()),
                ('day7_diet', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fitness_plans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
